version: '2'
services:
  discovery:
    build: ./coffeenet-discovery/
    ports:
      - "8761:8761"
    hostname: coffeenet-discovery.synyx.coffee

  ldap:
    build: ./ldap-ds-389/
    ports:
      - "38900:389"
    hostname: coffeenet-ldap.synyx.coffee
  auth:
    build: ./coffeenet-auth/
    ports:
      - "9999:9999"
    hostname: coffeenet-auth.synyx.coffee
    links:
      - discovery:coffeenet-discovery.synyx.coffee
      - ldap:coffeenet-ldap.synyx.coffee
      - graylog:coffeenet-logging.synyx.coffee
    depends_on:
      - ldap

  mongo:
    image: "mongo:3"
  elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
  graylog:
    image: graylog2/server:2.2.1-1
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"
    hostname: coffeenet-logging.synyx.coffee